version: '3.9'
services:
  web:
    build:
      context: .
    ports:
      - 8080:8080
    links:
      - php
  php:
    build:
      context: .
      dockerfile: php.Dockerfile
    env_file:
      - ".env"